export function getElements(doc = document) {
  return {
    frame: doc.getElementById("radarFrame"),
    mount: doc.getElementById("radarMount"),
    contactCount: doc.getElementById("contactCount"),
    threatLevel: doc.getElementById("threatLevel"),
    rangeValue: doc.getElementById("rangeValue"),
    noiseValue: doc.getElementById("noiseValue"),
    speed: doc.getElementById("speed"),
    range: doc.getElementById("range"),
    noise: doc.getElementById("noise"),
    angularResolution: doc.getElementById("angularResolution"),
    detectionProbability: doc.getElementById("detectionProbability"),
    falseAlarmRate: doc.getElementById("falseAlarmRate"),
    speedText: doc.getElementById("speedText"),
    rangeText: doc.getElementById("rangeText"),
    noiseText: doc.getElementById("noiseText"),
    angularResolutionText: doc.getElementById("angularResolutionText"),
    detectionProbabilityText: doc.getElementById("detectionProbabilityText"),
    falseAlarmRateText: doc.getElementById("falseAlarmRateText"),
    targetList: doc.getElementById("targetList"),
    log: doc.getElementById("log"),
    clock: doc.getElementById("clock"),
    addHostile: doc.getElementById("addHostile"),
    addResource: doc.getElementById("addResource"),
    lockNearest: doc.getElementById("lockNearest"),
    scramble: doc.getElementById("scramble"),
    hudTarget: doc.getElementById("hudTarget"),
    hudRange: doc.getElementById("hudRange"),
    hudDir: doc.getElementById("hudDir"),
    hudCoord: doc.getElementById("hudCoord"),
    hudStatus: doc.getElementById("hudStatus"),
    hudClass: doc.getElementById("hudClass"),
    hudVector: doc.getElementById("hudVector"),
    hudSignal: doc.getElementById("hudSignal"),
    lockBadge: doc.getElementById("lockBadge")
  };
}
