export const GAME_CONFIG = {
  version: "0.7",
  deadlines: [75, 220, 666, 2200, 12000],
  costs: {
    spin: 5,
  },
  rewards: {
    advanceCoins: 60,
    advanceTickets: 2,
    multiplierGrowth: 1.7,
    jackpotTickets: 5,
  },
  reels: {
    columns: 5,
    rows: 3,
    rowHeight: 84,
    extraRows: 1,
    stopDurations: [900, 1100, 1300, 1500, 1700],
    rowClasses: ["top", "mid", "bot"],
  },
  ui: {
    lineColors: ["#d4a020", "#40c8ff", "#ff80a0", "#9eff40", "#ffb347", "#a57cff", "#5df2d6", "#ff6b6b", "#ffe066", "#7fb3ff"],
    neutralBurst: "#6a5828",
    jackpotFlash: "#ff4020",
    jackpotBurst: "#d4a020",
    jackpotStars: "#ffdd40",
    devilFlash: "#cc00ff",
    devilTint: "#600030",
    depositBurst: "#30b060",
    gainFloat: "#d4a020",
    comboFloat: "#40c8ff",
    depositFloat: "#30b060",
    overdriveFlash: "#ff8a20",
    feverFlash: "#40c8ff",
    lossFlash: "#c03020",
  },
  items: {
    active: [
      {
        id: "lucky-clover",
        name: "Lucky Clover",
        summary: "Winning rows with clover get +50%.",
      },
      {
        id: "golden-bell",
        name: "Golden Bell",
        summary: "Bell line rewards echo one extra time.",
      },
      {
        id: "crown-reserve",
        name: "Crown Reserve",
        summary: "2+ crowns release reserve coins.",
      },
    ],
  },
  paylines: [
    {
      id: "line-1",
      label: "LINE 1",
      shortLabel: "L1",
      pathClass: "row0",
      resultClass: "win0",
      positions: [[0, 0], [1, 0], [2, 0], [3, 0], [4, 0]],
    },
    {
      id: "line-2",
      label: "LINE 2",
      shortLabel: "L2",
      pathClass: "row1",
      resultClass: "win1",
      positions: [[0, 1], [1, 1], [2, 1], [3, 1], [4, 1]],
    },
    {
      id: "line-3",
      label: "LINE 3",
      shortLabel: "L3",
      pathClass: "row2",
      resultClass: "win2",
      positions: [[0, 2], [1, 2], [2, 2], [3, 2], [4, 2]],
    },
    {
      id: "diag-down",
      label: "DIAG DOWN",
      shortLabel: "D1",
      pathClass: "diag0",
      resultClass: "win3",
      positions: [[0, 0], [1, 1], [2, 2], [3, 1], [4, 0]],
    },
    {
      id: "diag-up",
      label: "DIAG UP",
      shortLabel: "D2",
      pathClass: "diag1",
      resultClass: "win4",
      positions: [[0, 2], [1, 1], [2, 0], [3, 1], [4, 2]],
    },
    {
      id: "vert-1",
      label: "VERT 1",
      shortLabel: "V1",
      pathClass: "vert0",
      resultClass: "win5",
      positions: [[0, 0], [0, 1], [0, 2]],
    },
    {
      id: "vert-2",
      label: "VERT 2",
      shortLabel: "V2",
      pathClass: "vert1",
      resultClass: "win6",
      positions: [[1, 0], [1, 1], [1, 2]],
    },
    {
      id: "vert-3",
      label: "VERT 3",
      shortLabel: "V3",
      pathClass: "vert2",
      resultClass: "win7",
      positions: [[2, 0], [2, 1], [2, 2]],
    },
    {
      id: "vert-4",
      label: "VERT 4",
      shortLabel: "V4",
      pathClass: "vert3",
      resultClass: "win8",
      positions: [[3, 0], [3, 1], [3, 2]],
    },
    {
      id: "vert-5",
      label: "VERT 5",
      shortLabel: "V5",
      pathClass: "vert4",
      resultClass: "win9",
      positions: [[4, 0], [4, 1], [4, 2]],
    },
  ],
  symbols: [
    { id: "cherry", name: "Cherry", icon: "🍒", baseMultiplier: 2, baseWeight: 28, rarity: "common", family: "fruit" },
    { id: "lemon", name: "Lemon", icon: "🍋", baseMultiplier: 3, baseWeight: 22, rarity: "common", family: "fruit" },
    { id: "diamond", name: "Diamond", icon: "💎", baseMultiplier: 5, baseWeight: 16, rarity: "rare", family: "treasure" },
    { id: "clover", name: "Clover", icon: "🍀", baseMultiplier: 8, baseWeight: 11, rarity: "rare", family: "nature" },
    { id: "crown", name: "Crown", icon: "👑", baseMultiplier: 14, baseWeight: 7, rarity: "epic", family: "treasure" },
    { id: "bell", name: "Bell", icon: "🔔", baseMultiplier: 25, baseWeight: 5, rarity: "epic", family: "treasure" },
    { id: "devil", name: "Devil", icon: "😈", baseMultiplier: 0, baseWeight: 5, rarity: "curse", special: "devil", family: "infernal" },
    { id: "jackpot", name: "Seven", icon: "7️⃣", baseMultiplier: 60, baseWeight: 3, rarity: "legendary", special: "jackpot", family: "fate" },
  ],
};
